# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grand execute permission for gradlew # permission 에러가 발생할 경우
      run: chmod +x /root/actions-runner/_work/githubActionTutorial/githubActionTutorial/server/linode-github-action-test/gradlew

    - name: 환경변수 설정
      run: echo "${{ secrets.MY_APPLICATION_YML}}" > ./src/main/resources/application.yml
      working-directory: ./server/linode-github-action-test

    - name: build # 경로를 직접 설정하여 빌드 명령을 내려준다.
      run: /root/actions-runner/_work/githubActionTutorial/githubActionTutorial/server/linode-github-action-test/gradlew build
      working-directory: ./server/linode-github-action-test

    - name: Execute Jar File
      run: sudo kill -9 `sudo lsof -t -i:8080` & sudo java -jar /root/actions-runner/_work/githubActionTutorial/githubActionTutorial/server/linode-github-action-test/build/libs/linode-github-action-test-0.0.1-SNAPSHOT.jar &
